### ISSUE TITLE
create react app 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#1]

**Comment by AlexanderMalmstrom** [comment]
Hi!

Im wokring on this.

**Comment by monteirocamis** [comment]
Hi Alexander, I am sorry ! Didn´t see your Comment before the other PR !!
 thank you for your pull request! 
We are organizing more issues with photos to construct the pages with components.
Would be a pleasure have you working on this next ones

best regards,
Camis
