### ISSUE TITLE
⚠️ confirm: Integrate register page with API is working?

### ISSUE THREAD

**Issue by nirajpdn** [Codivas/portal-codivas#100]
# We can fill the form on register page but an error 400 / 404 shows , and we proceed to the portal 
- Is the registering working?
 - if yes, change the 400 to not allow member connect to the home page if 400 shows
 - if not , how can we fix it?

**Comment by monteirocamis** [comment]
![Captura de Tela 2022-10-29 às 01 18 59](https://user-images.githubusercontent.com/26682838/198813536-eb90a88c-1fff-4459-941e-51dae7f922e2.png)

**Comment by nirajpdn** [comment]
Okay the design will be improved and please check the latest issue #104

**Comment by monteirocamis** [comment]
We used the API to register in our landing page : 
https://github.com/Codivas/landing-codivas/blob/master/preregister.html
codivas.com.br

**Comment by monteirocamis** [comment]
Cadastro de usuário

cadastro do usuário

{
	"email": "mateus@exemple.com",
	"password": "125", #mandar em criptografado
	"user_name": "mateus"
}
import axios from "axios";

const options = {
  method: 'POST',
  url: 'https://proj-83c-codivas.herokuapp.com/users/registration/',
  headers: {'Content-Type': 'application/json'},
  data: {email: 'maria@codivas.com.br', password: '12345', user_name: 'maria'}
};

axios.request(options).then(function (response) {
  console.log(response.data);
}).catch(function (error) {
  console.error(error);
});

**Comment by nirajpdn** [comment]
@monteirocamis , could you please assign this to me

**Comment by nirajpdn** [comment]
> ![Captura de Tela 2022-10-29 às 01 18 59](https://user-images.githubusercontent.com/26682838/198813536-eb90a88c-1fff-4459-941e-51dae7f922e2.png)

Solved

**Comment by monteirocamis** [comment]
@nirajpdn  I think is working now, right? 
Do you know the endpoint to see every registered users? I created an issue for this documentation

**Comment by nirajpdn** [comment]
@monteirocamis, let me confirm.

**Comment by nirajpdn** [comment]
@monteirocamis , the 400 error is due to the users with that username or email already exists.
Need to show proper error message.

Let me do it so quick.
<img width="1182" alt="Screen Shot 2022-10-30 at 05 22 12" src="https://user-images.githubusercontent.com/59108522/198856340-c7301381-b89a-45f0-b978-f42912df5495.png">
