### ISSUE TITLE
Improve design & input fields in register page similar to login page.

### ISSUE THREAD

**Issue by nirajpdn** [Codivas/portal-codivas#104]

**Comment by monteirocamis** [comment]
## how is now:
![Captura de Tela 2022-10-29 às 01 28 08](https://user-images.githubusercontent.com/26682838/198813836-9f2d28a3-ed3b-4d19-ad48-7ea483237d8c.png)

## similar to the login page: 
![Captura de Tela 2022-10-29 às 01 28 37](https://user-images.githubusercontent.com/26682838/198813850-b0478d91-3ba9-4914-a58d-5bb3f170fd0c.png)

**Comment by nirajpdn** [comment]
@monteirocamis , Okay i will improve the design as well. Assign to me for now
