### ISSUE TITLE
📝 ⚠️🛑 URGENT: make a documentation of the APIs

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#108]
Our back end is wrking but the person ho made it do not documented =( 
please help up making in swagger or postman

**Comment by cjarett11** [comment]
How to begin ?

**Comment by EleekaN** [comment]
Hi @monteirocamis  Could you please elaborate what needs to be done.
 Looks like there is already a swagger documentation ...the link is there in the readme file.
