### ISSUE TITLE
change text button on footer 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#110]
## how is now
- we need to remove this "sobreNos"

![Captura de Tela 2022-10-29 às 15 30 31](https://user-images.githubusercontent.com/26682838/198847366-b0906ac9-953d-4b88-9c06-69c6e58f365d.png)

## how should be 
- only codivas link 
- in black color
- 
![Captura de Tela 2022-10-29 às 15 31 54](https://user-images.githubusercontent.com/26682838/198847425-36ec1e92-5e4d-487b-87fb-a80fba81e1b7.png)

**Comment by Anish-Sarawgi** [comment]
Can i work on this?

**Comment by monteirocamis** [comment]
Yes please @Anish-Sarawgi  !!
Thank you
