### ISSUE TITLE
add background image to sidebar

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#117]

**Comment by Matrix278** [comment]
Hello, you mean at this sidebar should be some image at the back, not the color as right now?
<img width="115" alt="image" src="https://user-images.githubusercontent.com/35573364/198883504-60a26a6e-ce28-49b2-af8c-bea5734796fe.png">

**Comment by Matrix278** [comment]
@monteirocamis I have made an [PR](https://github.com/Codivas/portal-codivas/pull/122) for that issue, could you check that out, is this was expected from this issue?
