### ISSUE TITLE
content |  projects Grid - Grid  de projetos 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#12]
🇺🇸 Now that we have the page for the projects, we need to include the content inside.
For it, we need a grid with cards 
Check the layout below and images on figma to develop
please let us now about any improvements in UI design for better code or Usability

🇧🇷 agora que já temos a página de projetos precisamos incluir o conteudo dentro.
para isso precisamos do grid de cards
veja o layout abaixo e as imagens para desenvolver 

done :
✔️  sidebar
✔️  footer
✔️  navbar

tasks:
🔴 title
🔴background color
🔴cards
🔴 arrows
🔴 buttons

🎨  
https://www.figma.com/file/1N3TVjL1CHdz8v9KSCWGJ5/Portal-Codivas?node-id=0%3A1

🖼️ 
![image](https://user-images.githubusercontent.com/26682838/135780946-ba9477eb-3ac4-48d0-829d-cf063d7095d3.png)

**Comment by kibi11** [comment]
Hey , I had some questions , how should the I do the arrow buttons on the sides , do have a image file for that. Or do you want to use css to make that

**Comment by kibi11** [comment]
I haven't worked with figma much, please help me with that.

**Comment by monteirocamis** [comment]
I have in mind something like this 
![image](https://user-images.githubusercontent.com/26682838/137245609-44879d07-6f50-4435-aaad-74c73f32aee9.png)

what you think? 
We accept any suggestions you have for us =)

**Comment by kibi11** [comment]
Hey @monteirocamis  , I have made a PR , do take a look.
