### ISSUE TITLE
create component page | contact - fale conosco

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#13]
## how is now

![Captura de Tela 2022-10-29 às 15 36 53](https://user-images.githubusercontent.com/26682838/198847594-15f158dc-2708-481b-8a5e-05a9edf9a14d.png)

## how should be. 
(the layout we have)  

![image](https://user-images.githubusercontent.com/26682838/135784021-1bd0eefa-4a1a-4da9-b405-fb0885b77adc.png)

**Comment by nisha331** [comment]
Hey @monteirocamis I would try to work on this, but where will i get that purple background?

**Comment by monteirocamis** [comment]
aah you can get ot from the figma.Do you know how to export images from there?
if not,no problem , I take for you and include here in some minutes

**Comment by nisha331** [comment]
Thanks @michelebarreto

**Comment by monteirocamis** [comment]
Hi @nisha331  Do you need help ? 😄
