### ISSUE TITLE
🟢  page | register - cadastre-se

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#15]
## Layout  :

![image](https://user-images.githubusercontent.com/26682838/135784154-b42b9efd-4dbd-4c58-8e51-274708ec191c.png)

**Comment by Nishith-Gohel** [comment]
Hello @monteirocamis shall I design this registration page ?

**Comment by monteirocamis** [comment]
![RegistrationPage](https://user-images.githubusercontent.com/26682838/136670091-27364837-c379-4d24-92d7-83d24ecb9a31.PNG)
