### ISSUE TITLE
component | sidebar 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#16]
🇺🇸  We need to include our menu sidebar with the pages of the panel admin
check below the layout and images to make it, if you need anything else let me know!
If you have some improvement, comment here with us!

🇧🇷 precisamos fazer o menu em sidebar com as paginas iniciais do projeto
veja abaixo o layout e pegue as imagens para criar
se precisar de algo mais me avise
se tiver melhorias comente aqui com a gente

🖼️ 
![image](https://user-images.githubusercontent.com/26682838/135773821-8a3fdbc3-e2bc-4205-a2f2-53349dbfa587.png)

🎨 
![Logo todo branco horinzontal 2](https://user-images.githubusercontent.com/26682838/135773790-e4ba816c-07a6-4c4a-96ad-689f665caea5.png)
![textura 2](https://user-images.githubusercontent.com/26682838/135773791-ab615fd4-1cb6-426b-b134-b7c2d6b3e7aa.png)

**Comment by kushalShukla-web** [comment]
can i contribute in this hactober contest

**Comment by ajishere07** [comment]
hey, @monteirocamis , I would like to build this component

**Comment by monteirocamis** [comment]
thank you guys!! make a pull on master because I just made some merge right now with footer and structure!

**Comment by monteirocamis** [comment]
let me include here the archives for sidebar 
Let´s organize the tasks for both can help on this issue? =)

**Comment by ajishere07** [comment]
@monteirocamis you have already added a sidebar named navigation, should come up with new sidebar.

**Comment by monteirocamis** [comment]
oh that's true 
another person made in inside of other issue 🤔
but we have the issue of menu dropdown

**Comment by monteirocamis** [comment]
oopps that's correct
another person made in other issue
sorry for that
but we have others issues 
I am opening today :)
