### ISSUE TITLE
feature | menu dropdown

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#20]
ENG: 
[  ] development - we need to construct this menu dropdown with links to profile page and  logout 

✔️  design - we want to edit this example for our brand colors and style , for it we need some designer or somebody to help us in color and font 

🇧🇷 
[  ] desenvolvimento - precisamos criar esse menu dropdown ao clicar no avatar do menu superior, abrindo um menu de links para perfil e logout
✔️ design - precisamos criar um layout como esse para o nosso site.No momento pegamos esse de um outro site mas precisamos colocar a nossa identidade codivas

🖼️  example of layout 
![image](https://user-images.githubusercontent.com/26682838/137393927-2ce71327-339f-4bdc-857c-24dbb516855c.png)

**Comment by Nishith-Gohel** [comment]
Hello @monteirocamis, I can help you with color and fonts, of your layout attached in the snapshot.

**Comment by Nishith-Gohel** [comment]
Could you assign the task to me ?

**Comment by monteirocamis** [comment]
sure thank you =)

**Comment by Nishith-Gohel** [comment]
@monteirocamis could please specify what kind of design do you expect for the brand, like what I actually need to design ?

**Comment by Nishith-Gohel** [comment]
Also could you throw some light on what to include in the design page, like sign in buttons, etc and also could you clarify what needs to be done in, dropdown with links ?

**Comment by monteirocamis** [comment]
@Nishith-Gohel  Can you just adjust the "pink" color more to "purple" ?  what you think ?

**Comment by monteirocamis** [comment]
![MenuDropdown](https://user-images.githubusercontent.com/26682838/136670098-f98165cc-2d99-4040-86a7-2fe6ef8e17bc.PNG)
