### ISSUE TITLE
mobile | footer bug

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#21]
🇺🇸  our responsive pages are almost perfect!! we just need to fix the itens on bottom right
🇧🇷 a parte responsiva ta quase prfeita, so precisa arrumar ali embaixo do aldo direito que quebrou os links
![image](https://user-images.githubusercontent.com/26682838/135777191-824be77b-c302-40f4-ab31-b5b2ae93f1cd.png)

**Comment by monteirocamis** [comment]
@nisha331 hey bud are you there?

**Comment by TaneliR** [comment]
I can probably fix this, at least I think I got them working correclty at some point in the other footer version. Would it be better to list them next to or on top of each other on mobile? 

I'll check the progress of this issue tomorrow and work something out if somebody hasn't fixed it already by then, if that's ok?

**Comment by monteirocamis** [comment]
hmmm I gues on bottom 
i'll make a little mockup for you :)
thank you

**Comment by nisha331** [comment]
Hey @michelebarreto let @TaneliR work on it. I just forgot about the mobile view. Ahh.
