### ISSUE TITLE
🟢  page | project detail - detalhes do projeto

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#22]
already have :
   ✅  sidebar 
   ✅   navbar
   ✅   footer 
 we need:
  🔴   center text 
  🔴    arrows
  🔴    buttons

🎨  https://www.figma.com/file/1N3TVjL1CHdz8v9KSCWGJ5/Portal-Codivas?node-id=0%3A1

![image](https://user-images.githubusercontent.com/26682838/135777749-78f39108-f8ca-43e5-a58f-c890e73e20c7.png)

**Comment by tusharkandpal** [comment]
Can i work on this ?
