### ISSUE TITLE
🟢  links | footer

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#29]
We need to include our links opening in another page for this area on footer like:
sobre nos - codivas.com.br
blog - blog.codivas.com.br
![image](https://user-images.githubusercontent.com/26682838/135939287-ec660483-c675-4ec4-ac4f-52cbfe00be58.png)

**Comment by thesahindia** [comment]
Hey! Do you want the footer links to open in another tab?

**Comment by monteirocamis** [comment]
yes! will be perfect =)

**Comment by DrunkOldDog** [comment]
Fixed in #30
