### ISSUE TITLE
🟢 page | forum home / inicio do forum

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#32]
🇺🇸  We are thinking about to create a section of the portal to make interactions with the members.
may be something similiar to "stackoverflow"... when you include a question, and people can answer that
We dont need everything for now, just the area of all questions , and in another issue I am going to make the question details page
🇧🇷 pensamos em fazer uma seção estilo "stackoverflow" onde a codiva abre com uma pergunta e as outras codivas seguem respondendo
não precisa ter tudo agora, pode ser so a area de todas as perguntas mesmo.E em outra issue vou colocar a pagina da pergunta
references :
![image](https://user-images.githubusercontent.com/26682838/136313498-dd2302e4-8189-4756-891d-b3bc34d0f47a.png)

**Comment by alepeglow** [comment]
que ideia maravilhosa *---*
