### ISSUE TITLE
styled-components | change our css to  styled-components library

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#48]
what you think about to include styled-components to make everything more fast and easy on styling?

**Comment by vishal5251** [comment]
Hi, can you explain me a bit more, then assign this one to me.

**Comment by monteirocamis** [comment]
@vishal5251  I will start on this issue, please send a pr about about you have made until now form me not to work on something you did =)

**Comment by vishal5251** [comment]
Assign me any part so that I can start ASAP!

**Comment by vishal5251** [comment]
Share some part of the project so that we can cover this issue.

**Comment by monteirocamis** [comment]
the login page is crashed =)
