### ISSUE TITLE
:green_circle:  styled-components | login page 

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#59]
the login page is with the style all broken

**Comment by monteirocamis** [comment]
@kibi11

**Comment by oneamanish** [comment]
see my pull req.

**Comment by mundadapurva** [comment]
@monteirocamis , I would like to work on this one.

**Comment by monteirocamis** [comment]
Hi @mundadapurva  , yes please =)) 
Thank you 
Let me know if you want to be in our meetings at gather.town
