### ISSUE TITLE
:green_circle:  styled-components | register page

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#60]
how is now:
![image](https://user-images.githubusercontent.com/26682838/140677602-2768c852-72c1-4fa4-afe8-806544290196.png)

__________________________________________________________-
how suppose to be:
![image](https://user-images.githubusercontent.com/26682838/140677570-2aa4dde9-1149-4a73-acff-baa4cb50e80b.png)

**Comment by Emiliano-Russo** [comment]
I can do it
we are talking only about the register account component right? 
because the header and footer go separately

**Comment by monteirocamis** [comment]
Yes @Emiliano-Russo 
after that you can make the header and footer from "outside" off the login area
