### ISSUE TITLE
link | forgot password page

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#61]
how is now:
- we don ´t have the " forgot password " page, so please add a link on the "esqueci a senha" .
The  person will can talk to us in WhatsApp +5511949230302

**Comment by Tejas-Teju** [comment]
Hi @monteirocamis,
Can you please include the problem with an image and the expected UI design and also describe the issue

**Comment by Matrix278** [comment]
Hi, I could add the link there.

**Comment by Matrix278** [comment]
@monteirocamis I have done this in [PR](https://github.com/Codivas/portal-codivas/pull/121), is this what you wanted to have within this issue?
