### ISSUE TITLE
🎨 styled-components | profile

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#62]
:red_circle: How is now / como está agora

![image](https://user-images.githubusercontent.com/26682838/139600406-71b1481c-ec3f-4476-ba3f-173d5592da9f.png)

:red_circle:  How it should be / como deveria ser
![image 16](https://user-images.githubusercontent.com/26682838/140625346-9e95c67f-b475-44e3-afc4-758a86eb046b.png)

___________________________________________________________________________

- [ ]  edit button from editar perfil
- [ ] edit title and message on intro banner
- [ ] change image from avatar
- [ ] change color background
- [ ] edit texts buttons from card avatar
- [ ] edit text positions and fonts from  card avatar

**Comment by aliraza944** [comment]
Please state the issue with the page?

**Comment by monteirocamis** [comment]
Hi @aliraza944 , I am organizing a layout to explain better  =)
I will include here

**Comment by aliraza944** [comment]
Alright cool...

**Comment by monteirocamis** [comment]
Heey @aliraza944  I updated now =)

Do you think it is possible  to make something similar to this design?

**Comment by aliraza944** [comment]
Yes, it's possible.
