### ISSUE TITLE
remove items from menu

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#88]
Please we need only for this launch the itens below :
- home
- codivas
- contato

# How is now : 
![Captura de Tela 2022-10-29 às 00 40 50](https://user-images.githubusercontent.com/26682838/198811586-54da78d8-c5f3-413d-981b-0f762aa01339.png)

## How needs to be:
![Captura de Tela 2022-10-28 às 23 40 37](https://user-images.githubusercontent.com/26682838/198783202-b24c682d-2a09-43d4-b1c3-4ba4c7f77db1.png)

**Comment by utkarsh4321** [comment]
@monteirocamis can you please assign this to me.

**Comment by Capalotty** [comment]
@monteirocamis....how are you doing??.... could you please assign this issue to me?

**Comment by Capalotty** [comment]
@monteirocamis .....are you removing those pages to insert into another page or we would be getting rid of them. Also where is the menu located??

**Comment by monteirocamis** [comment]
hey guys I am sorry but this issue received a PR today =/
But now you can check the next issues to start coding this pages please
