### ISSUE TITLE
Include profile link in this icon

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#89]
![Captura de Tela 2022-10-28 às 23 39 59](https://user-images.githubusercontent.com/26682838/198782895-dc65a5d5-24e6-47ad-aa08-a26f253e9ef4.png)

**Comment by nirajpdn** [comment]
Assign this to me as well

**Comment by nirajpdn** [comment]
@monteirocamis, registration doesn't work and i am not able to logged in to the system.
