### ISSUE TITLE
Add button "logout" in header

### ISSUE THREAD

**Issue by monteirocamis** [Codivas/portal-codivas#97]

**Comment by nirajpdn** [comment]
Want to work on this as well

**Comment by utkarsh4321** [comment]
Hii @monteirocamis can you assign this issue to me? I want to work on this.

**Comment by monteirocamis** [comment]
for sure @utkarsh4321  !!
Let us know if you are having any doubts or problems with this =) 
Thank you for your time

**Comment by monteirocamis** [comment]
@nirajpdn  let us know if you already made it please =)

**Comment by Matrix278** [comment]
Hi @monteirocamis, I have a solution for that issue, can I show you in PR?

**Comment by monteirocamis** [comment]
yes please @Matrix278  =)
