### ISSUE TITLE
Add "Don't have account ?  Register now" and add link to /registro  page

### ISSUE THREAD

**Issue by nirajpdn** [Codivas/portal-codivas#98]

**Comment by monteirocamis** [comment]
Thank you @nirajpdn !

**Comment by nirajpdn** [comment]
> Thank you @nirajpdn ! Would you like me to assign this issue for you ?

Sure @monteirocamis.

**Comment by monteirocamis** [comment]
I think this may help 

## Cadastro de usuário

cadastro do usuário

```javascript
{
	"email": "mateus@exemple.com",
	"password": "125", #mandar em criptografado
	"user_name": "mateus"
}
```

```javascript
import axios from "axios";

const options = {
  method: 'POST',
  url: 'http://127.0.0.1:8000/users/registration/',
  headers: {'Content-Type': 'application/json'},
  data: {email: 'maria@codivas.com.br', password: '12345', user_name: 'maria'}
};

axios.request(options).then(function (response) {
  console.log(response.data);
}).catch(function (error) {
  console.error(error);
});
```

**Comment by nirajpdn** [comment]
@monteirocamis, Thank you.

**Comment by monteirocamis** [comment]
I think the endpoint is https://proj-83c-codivas.herokuapp.com

**Comment by nirajpdn** [comment]
For login https://proj-83c-codivas.herokuapp.com is used.

**Comment by monteirocamis** [comment]
@isjanebea and @davinyvidal  made all this part from back end ... hey girls, come here to help us 💜

**Comment by nirajpdn** [comment]
> @isjanebea and @davinyvidal made all this part from back end ... hey girls, come here to help us 💜

@monteirocamis , I think backend is already done. I think the remaining part of integration to be done is from frontend side.

**Comment by monteirocamis** [comment]
Ah okay, I don´t now how to make it without a documentation in postman or swagger =(

Do you know?
